name: ${project.name}
main: io.github.dre2n.factionslwcbridge.FactionsLWCBridge
version: ${project.version}
author: Daniel Saukel
description: ${project.description}
website: ${project.url}
depend: [Factions, LWC]
